### ISSUE TITLE
Poco contraste en una configuración con esquema de color dark

### ISSUE THREAD

**Issue by stripTM** [mozhispania/mozhispania.github.io#1]
![imagen](https://github.com/mozhispania/mozhispania.github.io/assets/1289297/fcc673c1-fa96-45c7-8fcb-d542ffcde8c3)

En una configuración con esquema de color dark-mode, los textos que están dentro del `<main>` tienen muy poco contraste, parece que el problema es el background general que no se oscurece.

**Comment by pascalchevrel** [comment]
Corregido, gracias!
